version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db
  node-server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    container_name: node-server
    volumes:
      - ./server:/usr/src/apps/mern-ts-docker/server
      - /usr/src/apps/mern-ts-docker/server/node_modules
    depends_on:
      - mongo-db
  
  react-client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
    - 3000:3000
    container_name: react-client
    stdin_open: true
    volumes:
      - ./client:/usr/src/apps/mern-ts-docker/client
      - /usr/src/apps/mern-ts-docker/client/node_modules
    depends_on:
      - node-server
networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local